### PR TITLE
Hash passwords in database for security

### LINKED ISSUE #124: Encrypt passwords
**User Story**
As a user
I want my password to be stored in a secure fashion
So that my password is kept secret from other people and won't get hacked easily

**Priority**
- [x] High
- [ ] Medium
- [ ] Low

**Describe the solution you want to implement**
* Hash passwords on the sign up form in web-app before sending to the back-end
* Hash password on login and verify it makes the stored password (which should be hashed).
* Backend should only store hashed passwords 
* Document the new API changes if needed

**Describe alternatives you've considered**
n/a

**Issue Dependencies**
n/a

**Additional context**
Currently passwords are stored and used in plaintext.

### PR DESCRIPTION
**Pull request by timovv**
Passwords are no longer stored in plaintext increasing security.

Closes #124 

**Description**

- Altered database schema to add columns for password hash and salt 
- Passwords are now hashed + salted before storing in the database
- Instead of directly comparing passwords, implemented a function to test if the password is correct by testing if the hash is correct
- Added migration so that if a database exists with plaintext passwords, passwords will be hashed automatically without additional action required from the user 

**Testing**

Tested logging in and logging out using the web UI, tested creating an account, tested migration from existing database; updated and ran test_db unit test script to ensure database is working correctly.

**Checklist**

- [x] I have tested my change
- [x] Code builds successfully and all tests pass
- [x] Docs have been added/updated if needed -- will update docs on database schema when PR approved, there are no other important changes to documentation that I can see

### CODE REVIEW

**Review by ErnWong — APPROVED** [review]
I don't know much about `scrypt` and its parameters, but otherwise looks good to me.

**Review by ParieMalhotra — APPROVED** [review]
LGTM

**Comment by JamesUOA** [comment]
LGTM 👍

**Review by JamesUOA — APPROVED** [review]

**Review by joshiefu — APPROVED** [review]
Looks good to me!

**Pull request merged**
